.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH LLTAG 1 "DECEMBER 2005"



.SH NAME
lltag - tag mp3/ogg/flac music files automagically



.SH SYNOPSIS
.B lltag
.RB [ "-F <format>" ]
.RB [ -G ]
.RB [ -p ]
.RB [ "-a <artist>" ]
.RB [ "-t <title>" ]
.RB [ "-A <album>" ]
.RB [ "-n <number>" ]
.RB [ "-g <genre>" ]
.RB [ "-y <year>" ]
.RB [ "-c <comment>" ]
.RB [ --spaces ]
.RB [ --maj ]
.RB [ "--sep\ <s1|s2|...>" ]
.RB [ "--regexp <regexp>" ]
.RB [ --mp3/--ogg/--flac ]
.RB [ --clear ]
.RB [ --append ]
.RB [ --no-tagging ]
.RB [ "--rename <format>" ]
.RB [ --rename-ext ]
.RB [ --rename-min ]
.RB [ "--rename-sep <sep>" ]
.RB [ "--rename-regexp <regexp>" ]
.RB [ --dry-run ]
.RB [ --yes ]
.RB [ --ask ]
.RB [ -R ]
.RB [ -v ]
.RB [ "--config <file>" ]
.RB [ "--gencfg <file>" ]
.RB [ -S ]
.RB [ "--show-tags <tags>" ]
.RB [ -L ]
.RB [ -V ]
.RB [ -h ]
.\"



.SH DESCRIPTION
.B lltag
is a command-line tool to automagically set tags of MP3, OGG or FLAC files.
It parses the filenames according to different formats to get the tags.
The formats may be either given by the user or guessed by lltag from
its internal database.

When called with the
.B -F
option (once or multiple times), it will first try the user-specified formats.

Internal formats will be tried later if the
.B -G
option was passed.

.B mp3info
is used to tag
.B MP3
files while
.B vorbiscomment
is used for
.B OGG
files, and
.B metaflac
is used for
.B FLAC
files.

When called with
.B --rename
the target file will also be renamed.


.SH OPTIONS

.TP
.BI "-A, --album" " <album>"
Set the default value of the \fIAlbum\fR tag.

.TP
.BI "-a, --artist" " <artist>"
Set the default value of the \fIArtist\fR tag.

.TP
.BI "--append"
Force appending of ogg/flac tags
(instead of replacing existing tags).

Since mp3 files may only get one tag of each type, appending
does nothing, the first occurence only is stored.

.TP
.B --ask
Always ask confirmation to the user before tagging.
By default user-specified format matching is accepted
while guess format matching is asked for confirmation.
See
.B TAGGING CONFIRMATION
below for details.

.TP
.BI "-c, --comment" " <comment>"
Set the default value of the \fIComment\fR tag.

.TP
.B --clear
Force clearing of all tags before tagging
(instead of replacing existing tags).

.TP
.BI --config " <file>"
Parse additional configuration file.
See
.B CONFIGURATION FILES
below for details.

.TP
.B --dry-run
Do not really tag files, just show what would have been done.

.TP
.BI "-F, --format" " <format>"
Add the specified format string to the list of user-supplied formats.
Might be used several times to try different formats.
See
.B FORMAT
below for details.

.TP
.B --flac
Tag all files as FLAC files, using \fBmetaflac\fR.

.TP
.B "-G, --guess"
Guess format using the internal database if no user-specified format
worked (default behavior).

.TP
.BI "-g, --genre" " <genre>"
Set the default value of the \fIGenre\fR tag.

.TP
.BI --gencfg " <file>"
Generate configuration file.
See
.B CONFIGURATION FILES
below for details.

.TP
.B "-h, --help"
Print a usage message and exit.

.TP
.B "-L, --list"
List internal formats.

.TP
.B --maj
Upcase the first letter of each word in tags.

.TP
.B --mp3
Tag all files as MP3 files, using \fBmp3info\fR.

.TP
.BI "-n, --number" " <number>"
Set the default value of the \fITrack Number\fR tag.

.TP
.B --no-tagging
Do not actually tag files. This might be used to rename files
without tagging.

.TP
.B --ogg
Tag all files as OGG files, using \fBvorbiscomment\fR.

.TP
.B "-p, --nopath"
Do not consider the path of files when matching.

.TP
.B "-R, --recursive"
Recursively search for files in subdirectories.

.TP
.BI --regexp " <[tag,tag:]s/from/to/>"
Replace \fIfrom\fR with \fIto\fR in tags before tagging.
If several tags (comma-separated) prefix the regexp, replacement is
only applied to the corresponding fields.
This option might be used multiple times to specify multiple replacing.

.TP
.BI --rename " <format>"
After tagging, rename the file according to the format.
The format is filled using the first occurence of each tag that was
used to tag the file right before.
It means that an old existing tag may be used if no new one replaced
it and
.B --clear
was not passed.

By default, confirmation is asked before tagging.
See
.B RENAMING CONFIRMATION
below for details.

.TP
.B --rename-ext
Assume that the file extension is provided by the rename format
instead of automatically adding the extension corresponding to
the file type.

.TP
.B --rename-min
Lowcase all tags before renaming.

.TP
.BI --rename-regexp " <[tag,tag:]s/from/to/>"
Replace \fIfrom\fR with \fIto\fR in tags before renaming.
If several tags (comma-separated) prefix the regexp, replacement is
only applied to the corresponding fields.
This option might be used multiple times to specify multiple replacing.

.TP
.BI --rename-sep " <sep>"
Replace spaces with sep when renaming.
See
.B --rename-regexp
for a more general replace feature.

.TP
.B -S
Instead of tagging, lltag shows the tags that are currently set in
files.
See
.B --show-tags
to show only some tags.

.TP
.BI --sep " <string|string>"
Replace the specified characters or strings with space in tags.
They have to be |-separated.
See
.B --regexp
for a more general replace feature.

.TP
.BI --show-tags " <tag1,tag2,...>"
Instead of tagging, lltag shows tags that are currently set in files.
The argument is a comma separated list of tag types
.RI ( artist ", " title ", " album ", " number ", "
.IR genre ", " year ", " comment " or " all).
See also
.B -B
to show all tags.

.TP
.B --spaces
Allow multiple or no space instead of only one when matching.
Also allow spaces limiting path elements.

.TP
.BI "-t, --title" " <title>"
Set the default value of the \fITitle\fR tag.

.TP
.B "-v, --verbose"
Show verbose messages.

.TP
.B "-V, --version"
Show the version.

.TP
.BI "-y, --year" " <year>"
Set the default value of the \fIYear\fR tag.

.TP
.B --yes
Always accept tagging without asking the user.
By default user-specified format matching is accepted
while guess format matching is asked for confirmation.

Also always accept renaming without asking the user.



.SH FORMAT
User-specified formats must be a string composed of any characters
and the following special codes:
.RS

.I "%a"
to match the author.

.I "%A"
to match the album.

.I "%g"
to match the genre.

.I "%n"
to match the track number.

.I "%t"
to match the title.

.I "%y"
to match the year.

.I "%c"
to match the comment.

.I "%d"
to match anything and forget it.

.I "%%"
to match %.



.SH TAGGING CONFIRMATION
When
.B --ask
is passed or when guessing, each matching will lead to
a confirmation message before tagging.
Available behaviors are:

.I y
.RS
Tag current file with current format.
This is the default reply (that is why \fI<y>\fR appears).
.RE

.I v
.RS
View which tags would be set.
.RE

.I u
.RS
Tag current file with current format.
Then use current format for all remaining matching files.
When a non-matching file is reached, stop using this
preferred format.
.RE

.I a
.RS
Tag current file with current format.
Then, never asking for a confirmation anymore.
.RE

.I e
.RS
Edit current fields before tagging, see \fBEDITING TAGS\fR.
.RE

.I n
.RS
Don't tag current file with this format.
Try the next matching format on the current file.
.RE

.I p
.RS
When matching is done through combination of a path parser
and a basename parser, keep the basename parser and try the
next path parser on the current file.
.RE

.I s
.RS
Skip the current file, don't tag it at all.
.RE

.I h
.RS
Show help about confirmation.
.RE


.SH EDITING TAGS

It is possible to edit tags during matching confirmation.
It includes fields that were matched by the format, default values
and other fields.
The current value of all regular fields is shown and may be modified
or cleared.

The behavior depends on the installed readline library.
If it is smart, the current value may be edited inline and an
history is available.
If not, pressing
.I <enter>
will keep the current value while
.I CLEAR
will empty it.
.RE

Each field may be selected for edition by pressing its corresponding
letter in the format (see \fBFORMAT\fR).
Editing ends by tagging (if \fIE\fR is pressed)
or canceling and return to confirmation menu (if \fIC\fR is pressed).



.SH RENAMING CONFIRMATION
By default, before renaming, a confirmation is asked to the user.
You may bypass it by passing
.B --yes
on the command line.

If the rename format uses a field that is not defined,
a warning is shown and confirmation is always asked.

Available behaviors when renaming are:

.I y
.RS
Rename current file with current new filename.
This is the default reply (that is why \fI<y>\fR appears).
.RE

.I a
.RS
Rename current file with current new filename.
Then, never asking for a renaming confirmation anymore.
.RE

.I e
.RS
Edit current new filename before renaming.
The behavior depends on the installed readline library.
If it is smart, the current value may be edited inline
and an history is available.
.RE

.I n
.RS
Don't rename current file.
.RE

.I h
.RS
Show help about confirmation.
.RE



.SH INTERNAL FORMATS
The internal format database is usually stored in
.IR /etc/lltag/formats .
The user may override this file by defining a
.IR $HOME/.lltag/formats .
If this file exists, the system-wide one is ignored.

These files contain entries composed of :

.RE
.I [%n - %a - %t]
.RS
A title between bracket
.RE
.I type = basename
.RS
The type is either
.I basename
or
.I path
.RE
.I regexp = %L%N%S-%S%A%S-%S%A%L
.RS
A format composed of %L for limiting space, %N for numbers, %S for a space,
%A for anything (except /), %P for any path and %% for %.
.RE
.I indices = n,a,t
.RS
A list of format letters corresponding to %N or %A field in the previous format
(See
.B FORMAT
for a list of these letters).



.SH CONFIGURATION FILES
lltag reads some configuration files before parsing command line options.
The system-wide configuration file is defined in
.I /etc/lltag/config
where all options are documented.

It also reads
.I $HOME/.lltag/config
if it exists.

The user may also add another configurable file with
.B --config .

lltag may also generate a configuration with
.B --gencfg .

The available options are :

.I format = \fI"string"
.RS
Add a user-defined format
.RB [ -R ].
Might be used multiple times.
Default is to guess if no user-defined formats and no default field values are given.
.RE
.I guess = <0/1>
.RS
Try to guess if user-defined formats do not match
.RB [ -G ].
Default is
.BR 0 " (" disabled ") when no user-defined formats and no default field values are given."
.RE
.I nopath = <0/1>
.RS
Do not use file path when matching filename
.RB [ -p ].
Default is
.BR 0 " (" disabled ")."
.RE
.I default_ARTIST = \fI"string"
.RE
.I default_TITLE = \fI"string"
.RE
.I default_ALBUM = \fI"string"
.RE
.I default_NUMBER = \fI"string"
.RE
.I default_GENRE = \fI"string"
.RE
.I default_YEAR = \fI"string"
.RE
.I default_COMMENT = \fI"string"
.RS
Default field value
.RB [ -a ", " -t ", " -A ", " -n ", " -g ", " -y " and " -c ].
Default is to not set any default value.
.RE
.I spaces = <0/1>
.RS
Allow no or multiple spaces
.RB [ --spaces ].
Default is
.BR 0 " (" disabled ")."
.RE
.I maj = <0/1>
.RS
Upcase first letters of words in tags
.RB [ --maj ].
Default is
.BR 0 " (" disabled ")."
.RE
.I regexp = \fI"s/from/to/"
.RS
Replace \fIfrom\fR with \fIto\fR in all tags.
.I title,number:s/from/to/
replaces in title and number tags only.
Might be used multiple times
.RB [ --regexp ].
Default is to not apply any regexp.
.RE
.I sep = \fI"string"
.RS
Replace |-separated strings with space in tags.
Default is to not replace any separator.
.RE
.I type = <mp3|ogg|flac|none>
.RS
Force mp3, ogg of flac instead of by-extension detection
.RB [ --mp3 ", " --ogg " and " --flac ].
Default is
.BR none .
.RE
.I clear_tags = <0/1>
.RS
Clear all tags of audio files.
.BR [ --clear ].
Default is
.BR 0 " (" disabled ")."
.RE
.I append_tags = <0/1>
.RS
Append tags only instead of replacing old ones.
.RB [ --append ].
Default is
.BR 0 " (" disabled ")."
.RE
.I no_tagging = <0/1>
.RS
Do not actually tag files
.RB [ --no-tagging ].
Default is
.BR 0 " (" disabled ")."
.RE
.I rename_format = \fI"string"
.RS
Rename file according to format
.RB [ --rename ].
Default is to not rename.
.RE
.I rename_min = <0/1>
.RS
Lowcase tags before renaming
.RB [ --rename-min ].
Default is
.BR 0 " (" disabled ")."
.RE
.I rename_regexp = \fI"s/from/to/"
.RS
Replace \fIfrom\fR with \fIto\fR in all tags before renaming.
.I title,number:s/from/to/
replaces in title and number tags only.
Might be used multiple times
.RB [ --rename-regexp ].
Default is to not apply any regexp.
.RE
.I rename_sep = \fI"string"
.RS
Replace space with s in tags before renaming
.RB [ --rename-sep ].
Default is to not replace any separator.
.RE
.I rename_ext = <0/1>
.RS
Assume the rename format provides an extension
.RB [ --rename-ext ].
Default is
.BR 0 " (" disabled ")."
.RE
.I dry_run = <0/1>
.RS
Do nothing but show what would have been done
.RB [ --dry-run ].
Default is
.BR 0 " (" disabled ")."
.RE
.I yes = <0/1>
.RS
Tag without asking for confirmation when guessing
and rename without asking for confirmation
.RB [ --yes ].
Default is
.BR 0 " (" disabled ")."
.RE
.I ask = <0/1>
.RS
Always ask for confirmation before tagging
.RB [ --ask ].
Default is
.BR 0 " (" disabled ")."
.RE
.I recursive = <0/1>
.RS
Recursively traverse all given subdirectories
.RB [ -R ].
Default is
.BR 0 " (" disabled ")."
.RE
.I verbose = <0/1>
.RS
Verbose messages
.RB [ -v ].
Default is
.BR 0 " (" disabled ")."



.SH FILES
.RE
.I /etc/lltag/formats
.RS
System-wide internal format database.
See
.B INTERNAL FORMATS
for details.
.RE
.I $HOME/.lltag/formats
.RS
User internal format database. If it exists, the system-wide one is ignored.
.RE
.I $HOME/.lltag/edit_history
.RS
History of last entered values in the edition mode if the
.B Readline
library supports this feature.
.RE
.I /etc/lltag/config
.RS
System-wide configuration file, with documentation.
See
.B CONFIGURATION FILES
for details.
.RE
.I $HOME/.lltag/config
.RS
User configuration file.



.SH AUTHOR
Brice Goglin
