.TH LLTAG 1 "March 2005"
.\"
.SH NAME
lltag \- tag mp3/ogg music files automagically
.br
.\"
.SH SYNOPSIS
.B lltag
.RB [ \-F\ format ]
.RB [ \-G ]
.RB [ \-R ]
.RB [ \-p ]
.RB [ \-a\ artist ]
.RB [ \-t\ title ]
.RB [ \-A\ album ]
.RB [ \-n\ number ]
.RB [ \-g\ genre ]
.RB [ \-y\ year ]
.RB [ \-\-yes ]
.RB [ \-\-ask ]
.RB [ \-\-mp3/\-\-ogg ]
.RB [ \-\-dry\-run ]
.RB [ \-L ]
.RB [ \-V ]
.RB [ \-v ]
.RB [ \-h ]
.\"


.SH DESCRIPTION
.B lltag
is a command-line tool to automagically set tags of
MP3 or OGG files.
It parses the filenames according different formats
to get the tags.
The formats may be either given by the user or guessed
by
.B lltag
from its internal database.

When called with the
.B \-F
option (once or multiple times), it will first try
the user-specified formats.

Internal formats will be tried later if the
.B \-G
option was passed.

\fImp3info\fR is used to tag MP3 files while
\fIvorbiscomment\fR is used for OGG files.


.SH OPTIONS
.TP
.I "\-A, \-\-album album"
Set the default value of the \fIAlbum\fR tag.
.TP
.I "\-a, \-\-artist artist"
Set the default value of the \fIArtist\fR tag.
.TP
.I "\-\-ask"
Always ask confirmation to the user before tagging.
By default user-specified format matching is accepted
while guess format matching is asked for confirmation.
See
.SM
.B CONFIRMATION
below for details.
.TP
.I "\-\-dry\-run"
Do not really tag files, just show what would have been done.
.TP
.I "\-F, \-\-format format"
Add the specified format string to the list of user-supplied formats.
Might be used several times to try different formats.
See
.SM
.B FORMAT
below for details.
.TP
.I "\-G, \-\-guess"
Guess format using the internal database if no user-specified format
worked (default behavior).
.TP
.I "\-g, \-\-genre genre"
Set the default value of the \fIGenre\fR tag.
.TP
.I "\-h, \-\-help"
Print a usage message and exit.
.TP
.I "\-L, \-\-list"
List internal formats.
.TP
.I "\-\-mp3"
Tag all files as MP3 files, using \fImp3info\fR.
.TP
.I "\-n, \-\-number number"
Set the default value of the \fITrack Number\fR tag.
.TP
.I "\-\-ogg"
Tag all files as OGG files, using \fIvorbiscomment\fR.
.TP
.I "\-p, \-\-nopath"
Do not consider the path of files when matching.
.TP
.I "\-R, \-\-recursive"
Recursively search for files in subdirectories.
.TP
.I "\-\-sep string|string"
Replace the specified characters or strings with space in tags.
They have to be |-separated.
.TP
.I "\-\-spaces"
Allow multiple or no space instead of only one when matching.
Also allow spaces limiting path elements.
.TP
.I "\-t, \-\-title title"
Set the default value of the \fITitle\fR tag.
.TP
.I "\-v, \-\-verbose"
Show verbose messages.
.TP
.I "\-V, \-\-version"
Show the version.
.TP
.I "\-y, \-\-year year"
Set the default value of the \fIYear\fR tag.
.TP
.I "\-\-yes"
Always accept tagging without asking the user.
By default user-specified format matching is accepted
while guess format matching is asked for confirmation.


.SH FORMAT
User-specified formats must be a string composed of any characters
and the following special codes:
.RS

.I "%a"
to match the author.

.I "%A"
to match the album.

.I "%g"
to match the genre.

.I "%n"
to match the track number.

.I "%t"
to match the title.

.I "%y"
to match the year.

.I "%d"
to match anything and forget it.

.I "%%"
to match %.

.SH CONFIRMATION
When --ask is passed or when guessing, each matching will lead to
a confirmation message before tagging.
Available behavior are:
    
.B y
.RS
Tag current file with current format.
.RE

.B v
.RS
View which tags would be set.
.RE

.B u
.RS
Tag current file with current format.
Then use current format for all remaining matching files.
When a non-matching file is reached, stop using this
preferred format.
.RE

.B a
.RS
Tag current file with current format.
Then, never asking for a confirmation anymore.
.RE

.B e
.RS
Edit current fields before tagging, including fields
that are non matched by the format, and default values.
Editing ends by tagging or canceling (return to confirmation menu).
.RE

.B n
.RS
Don't tag current file with this format.
Try the next matching format on the current file.
.RE

.B p
.RS
When matching is done through combination of a path parser
and a filename parser, keep the filename parser and try the
next path parser on the current file.
.RE

.B s
.RS
Skip the current file, don't tag it at all.
.RE

.B h
.RS
Show help about confirmation.
.RE


.SH INTERNAL FORMATS
The internal format database is usually stored in
.IR "/etc/lltag/format" .
It contains entries composed of :

.RE
.I [%n - %a - %t]
.RS
A title between bracket
.RE
.I type = filename
.RS
The type is either
.IR filename
or
.IR "path"
.RE
.I regexp = %L%N%S-%S%A%S-%S%A%L
.RS
A format composed of %L for limiting space, %N for numbers, %S for a space,
%A for anything (except /), %P for any path and %% for %.
.RE
.I indices = n,a,t
.RS
A list of format letters corresponding to %N or %A field in the previous format
(See
.SM
.B FORMAT
for a list of these letters).


.SH FILES
.RE
.I /etc/lltag/format
.RS
System-wide internal format database. See
.SM
.B INTERNAL FORMATS
for details.

.SH AUTHOR
Brice Goglin, <Brice.Goglin@ens-lyon.org>
.br
