.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH LLTAG 1 "NOVEMBER 2006"





.SH NAME
lltag - tag and rename mp3/ogg/flac music files automagically




.SH SYNOPSIS
.B lltag
.RB [ -C ]
.RB [ -E ]
.RB [ "-F <format>" ]
.RB [ -G ]
.RB [ -p ]
.RB [ "-a <artist>" ]
.RB [ "-t <title>" ]
.RB [ "-A <album>" ]
.RB [ "-n <number>" ]
.RB [ "-g <genre>" ]
.RB [ "-d <date>" ]
.RB [ "-c <comment>" ]
.RB [ "--tag <TAG=value>" ]
.RB [ --spaces ]
.RB [ --maj ]
.RB [ "--sep\ <s1|s2|...>" ]
.RB [ "--regexp <regexp>" ]
.RB [ --mp3/--ogg/--flac ]
.RB [ "--type <type>" ]
.RB [ --clear ]
.RB [ --append ]
.RB [ --no-tagging ]
.RB [ "--rename <format>" ]
.RB [ --rename-ext ]
.RB [ --rename-min ]
.RB [ "--rename-sep <sep>" ]
.RB [ "--rename-regexp <regexp>" ]
.RB [ --dry-run ]
.RB [ --yes ]
.RB [ --ask ]
.RB [ "--cddb-query <query>" ]
.RB [ "--cddb-server <server[:port]>" ]
.RB [ -R ]
.RB [ -v ]
.RB [ -q ]
.RB [ "--config <file>" ]
.RB [ "--gencfg <file>" ]
.RB [ -S ]
.RB [ "--show-tags <tags>" ]
.RB [ -L ]
.RB [ -V ]
.RB [ -h ]
.RB files...
.\"




.SH DESCRIPTION
.B lltag
is a command-line tool to automagically set tags of MP3, OGG or FLAC
files. There are several ways to obtains the tags that will be set:

.TP
.B Parsing the filename
.B lltag
may either parse the filename using its own internal database
of commonly-used formats (default behavior, or when
.B -G
is passed), or some user-provided formats (when
.B -F
is passed).

.TP
.B Requesting from CDDB
.B lltag
may access an online CDDB database to extract tags from a track of a CD (when
.B -C
is passed).

.TP
.B Explicitly setting values
.B lltag
provides a set of command-line option to manually set various tags.

.TP
.B Manually editing values
.B lltag
provides an interactive interface to edit existing values
or any value provided by the above strategies.

.P
Each time, a new audio file is processed,
.B lltag
starts by trying to obtain new tags depending on the behavior options
given by the user.

First, if a preferred parser has been selected before, it is used to try
to parse the new filename.
Then, if editing is enabled
.RB ( -E ),
the user will be able to modify existing tag values.
Then, if CDDB is enabled
.RB ( -C ),
the user will be asked to request tags from the
online CDDB database.
Then, if the user provided any parsing format
.RB ( -F ),
or if guessing is enabled
.RB ( -G ),
.B lltag
will attempt to parse the filename.

Note that if no behavior is chosen at all on command-line, including no
renaming option, then parsing with the internal format database will be
used by default (as if
.B -G
had been passed).

As soon as one of the above strategies succeeds,
.B lltag
jumps to the main menu
where the user may either accept new tags or select another behavior (see
.B MAIN MENU
in
.B INTERACTIVE MENUS
below for details).
If
.B --yes
has been passed, or if automatic mode has been previously enabled in the menu,
it will proceed with tagging (and renaming if requested) and go on with the
next file.

The new tags that the selected strategy returns will be appended with
the additional values given with
.BR --tag .
They will then either replace (default), clear and replace
.RB ( --clear )
or append to
.RB ( --append )
the existing tags in the target file.
And finally, each tag that will not be defined (and which the user will
have provided a default value for, with
.BR -a ", " -t ", " -A ", " -g ", " -n ", " -d " or " -c )
will get a default value.

Once the tags are known, a backend program or library is used to apply
them to the audio file (unless
.B --no-tagging
is passed).
.RB "The " MP3::Tag " Perl module or " mp3info
is used to tag
.B MP3
files while
.B vorbiscomment
is used for
.B OGG
files, and
.B metaflac
is used for
.B FLAC
files.

In the end, when called with
.BR --rename ,
the target file will also be renamed according to a user-provided format
filled with the tag values.




.SH OPTIONS

.TP
.BI "-A, --album" " <album>"
Set the default value of the \fIALBUM\fR tag.
The corresponding configuration file option is
.IR default_ALBUM .

.TP
.BI "-a, --artist" " <artist>"
Set the default value of the \fIARTIST\fR tag.
The corresponding configuration file option is
.IR default_ARTIST .

.TP
.BI "--append"
Force appending of ogg/flac tags
(instead of replacing existing tags).
The corresponding configuration file option is
.IR append_tags .

Since mp3 files may only get one tag of each type, appending
does nothing, the first occurence only is stored.

.TP
.B --ask
Always ask confirmation to the user before using a user-specified
parser. By default, all actions require confirmation, except when
a matching user-specified format is found.
The corresponding configuration file option is
.IR ask .
See
.B PARSING MENU
in
.B INTERACTIVE MENUS
below for details.

.TP
.B "-C, --cddb"
Try to find tags in the CDDB online database before trying to parse filenames.
The queries are sent using the HTTP interface, which means a HTTP proxy might
be used when required.
The corresponding configuration file option is
.IR cddb .

.TP
.BI "--cddb-query" " <keywords>"
.TP
.BI "--cddb-query" " <cat>/<id>"
Automatically search for CD matching <keywords> or matching category <cat>
and id <id>
as if the user passed
.B --cddb
and entered the query interactively in the module.

.TP
.BI "--cddb-server" " <server[:port]>"
Change the CDDB server, and eventually its port.
The default is
.BR www.freedb.org:80 .
The corresponding configuration file options are
.IR cddb_server_name " and " cddb_server_port .
If a HTTP proxy is required to access the internet,
the environment variable
.B HTTP_PROXY
may be used (set to something like "http://my.proxy.com").

.TP
.BI "-c, --comment" " <comment>"
Set the default value of the \fICOMMENT\fR tag.
The corresponding configuration file option is
.IR default_COMMENT .

.TP
.B --clear
Force clearing of all tags before tagging
(instead of replacing existing tags).
The corresponding configuration file option is
.IR clear_tags .

.TP
.BI --config " <file>"
Parse additional configuration file.
See
.B CONFIGURATION FILES
below for details.

.TP
.BI "-d, --date" " <date>"
Set the default value of the \fIDATE\fR tag.
The corresponding configuration file option is
.IR default_DATE .
Note that the ID3 date tag may only store 4 characters (for a year).

.TP
.B --dry-run
Do not really tag files, just show what would have been done.
The corresponding configuration file option is
.IR dry_run .

.TP
.B -E, --edit
Edit tags immediately.

.TP
.BI "-F, --format" " <format>"
Add the specified format string to the list of user-supplied formats.
The corresponding configuration file option is
.IR format .
Might be used several times to try different formats.
See
.B FORMAT
below for details.

.TP
.B --flac
Tag all files as FLAC files, using the FLAC backend (based on \fBmetaflac\fR).
The corresponding configuration file option is
.IR type .

.TP
.B "-G, --guess"
Guess format using the internal database if no user-specified format
worked (default behavior).
The corresponding configuration file option is
.IR guess .

.TP
.BI "-g, --genre" " <genre>"
Set the default value of the \fIGENRE\fR tag.
The corresponding configuration file option is
.IR default_GENRE .
While some file types accept any string as a genre, some others
(especially ID3v1 tags in MP3 files) require the string to match
within a list of specified genres.

.TP
.BI --gencfg " <file>"
Generate configuration file.
See
.B CONFIGURATION FILES
below for details.

.TP
.B "-h, --help"
Print a usage message and exit.

.TP
.B "-L, --list"
List internal formats.

.TP
.B --maj
Upcase the first letter of each word in tags.
The corresponding configuration file option is
.IR maj .

.TP
.B --mp3
Tag all files as MP3 files, using the MP3 backend
(based on either \fBmp3info\fR or \fBMP3::Tag\fR).
The corresponding configuration file option is
.IR type .

.TP
.B --mp3v2
Enable the experimental MP3 ID3v2-aware backend (based on \fRMP3::Tag\fR)
instead of the old ID3v1-only backend.

.TP
.B --mp3read=[1][2]
Configure how the MP3v2 backend reads and merges ID3v1 and v2 tags.
By default, v1 are appended to v2 (\fB21\fR).
If set to \fB1\fR, only v1 are read.
If set to \fB2\fR, only v2 are read.
If set to \fB12\fR, v2 are appended to v1.
Note that merging/appending takes care of removing duplicates.

.TP
.BI "-n, --number" " <number>"
Set the default value of the \fINUMBER\fR tag.
The corresponding configuration file option is
.IR default_NUMBER .

.TP
.B --no-tagging
Do not actually tag files. This might be used to rename files
without tagging.
The corresponding configuration file option is
.IR no_tagging .

.TP
.B --ogg
Tag all files as OGG files, using the OGG backend (based on \fBvorbiscomment\fR).
The corresponding configuration file option is
.IR type .

.TP
.B "-p, --no-path"
Do not consider the path of files when matching.
The corresponding configuration file option is
.IR no_path .

.TP
.B "-q, --quiet"
Decrease message verbosity.
The corresponding configuration file option is
.I verbose
which indicates the verbose level.
See
.BR -v
for details about the existing verbosity levels.

.TP
.B "-R, --recursive"
Recursively search for files in subdirectories that are given on
the command line.
The corresponding configuration file option is
.IR recursive .

.TP
.BI --regexp " <[tag,tag:]s/from/to/>"
Replace \fIfrom\fR with \fIto\fR in tags before tagging.
The corresponding configuration file option is
.IR regexp .
If several tags (comma-separated) prefix the regexp, replacement is
only applied to the corresponding fields.
This option might be used multiple times to specify multiple replacing.

.TP
.BI --rename " <format>"
After tagging, rename the file according to the format.
The corresponding configuration file option is
.IR rename_format .
The format is filled using the first occurence of each tag that was
used to tag the file right before.
It means that an old existing tag may be used if no new one replaced
it and
.B --clear
was not passed.

By default, confirmation is asked before tagging.
See
.B RENAMING MENU
in
.B INTERACTIVE MENUS
below for details.

.TP
.B --rename-ext
Assume that the file extension is provided by the rename format
instead of automatically adding the extension corresponding to
the file type.
The corresponding configuration file option is
.IR rename_ext .

.TP
.B --rename-min
Lowcase all tags before renaming.
The corresponding configuration file option is
.IR rename_min .

.TP
.BI --rename-regexp " <[tag,tag:]s/from/to/>"
Replace \fIfrom\fR with \fIto\fR in tags before renaming.
If several tags (comma-separated) prefix the regexp, replacement is
only applied to the corresponding fields.
This option might be used multiple times to specify multiple replacing.
The corresponding configuration file option is
.IR rename_regexp .

.TP
.BI --rename-sep " <sep>"
Replace spaces with sep when renaming.
The corresponding configuration file option is
.IR rename_sep .
See
.B --rename-regexp
for a more general replace feature.

.TP
.B -S
Instead of tagging, lltag shows the tags that are currently set in
files.
See
.B --show-tags
to show only some tags.

.TP
.BI --sep " <string|string>"
Replace the specified characters or strings with space in tags.
The corresponding configuration file option is
.IR sep .
They have to be |-separated.
See
.B --regexp
for a more general replace feature.

.TP
.BI --show-tags " <tag1,tag2,...>"
Instead of tagging, lltag shows tags that are currently set in files.
The argument is a comma separated list of tag types
.RI ( artist ", " title ", " album ", " number ", "
.IR genre ", " date ", " comment " or " all ).
See also
.B -S
to show all tags.

.TP
.B --spaces
Allow multiple or no space instead of only one when matching.
Also allow spaces limiting path elements.
The corresponding configuration file option is
.IR spaces .
See also
.B INTERNAL FORMATS
to get the detailled impact of this option.

.TP
.BI "-t, --title" " <title>"
Set the default value of the \fITITLE\fR tag.
The corresponding configuration file option is
.IR default_TITLE .

.TP
.BI "--tag" " <TAG=value>"
Add an additional tag.
The corresponding configuration file option is
.IR tag .
Might be used several times.
Note that mp3 tags do not support whatever
.IR TAG .

.TP
.BI "--type" " <type>"
Tag all files as
.B <type>
files.
The corresponding configuration file option is
.IR type .

.TP
.B "-v, --verbose"
Increase message verbosity.
The corresponding configuration file option is
.I verbose
which indicates the verbose level.

The default verbosity level is 0 to show only important messages.
Other possible values are 1 to show usage information when a menu
is displayed for the first time, and 2 to always show usage
information before a menu appears.

See also
.BR -q .

.TP
.B "-V, --version"
Show the version.

.TP
.B --yes
Always accept tagging without asking the user.
The corresponding configuration file option is
.IR yes .
By default user-specified format matching is accepted
while guess format matching is asked for confirmation.

Also always accept renaming without asking the user.




.SH INTERACTIVE MENUS
When not running with
.BI --yes ,
the user has to tells lltag what to do.
Files are processed one after the other, with the following steps:
.TP
.B *
If the
.B preferred
parser exists, try to apply it.
.TP
.B *
If failed, if
.B --cddb
was passed, trying a CDDB query.
.TP
.B *
If failed, try the user-provided formats, if any.
.TP
.B *
If failed, if no user-format were passed, or if
.B -G
was passed, try the internal formats.
.TP
.B *
Then we have a list of tags to apply, we may apply them, edit them,
or go back to a CDDB query or trying to parse the filename again.
.TP
.B *
Then, if
.B --rename
was passed, the file is renamed.

When hitting
.B Ctrl-d
at the beginning of an empty line
.RB ( EOF ),
the general behavior is to cancel the current operation
without leaving.

We now describe all interactive menus in detail.




.SS MAIN MENU
Once some tags have been obtained by either CDDB, parsing or the default
values on the command line, the main menu opens to either change the tags
or apply them:
.TP
.B y
Yes, use these tags (default)
.TP
.B a
Always yes, stop asking for a confirmation
.TP
.B P
Try to parse the file, see
.B PARSING MENU
.TP
.B C
Query CDDB, see
.B CDDB MENUS
.TP
.B E
Edit values, see
.B EDITING MENU
.TP
.B D
Only use default and additional values, forget about CDDB or parsed tags
.TP
.B Z
Reset to no tag values at all
.TP
.B R
Revert to existing tag values from the current file
.TP
.B O
Display existing tag values in the current file
.TP
.B n
Do not tag this file, jump to renaming (or to the next file if renaming is disabled)
.TP
.BR q " (or " EOF )
Skip this file
.TP
.B Q
Quit without tagging anything anymore



.SS CDDB MENUS
When the CDDB opens for the first time, the user must enter a query
to choose a CD in the online database.
.TP
.B <space-separated keywords>
CDDB query for CD matching the keywords.
Search in all CD categories within fields artist OR album.

.\" freedb.org specific manual, not used anymore
.\"Search in all CD categories within fields artist and title by default.
.\"If
.\".B cats=foo+bar
.\"is added, search in CD categories foo and bar only.
.\"If
.\".B fields=all
.\"is added, search keywords in all fields.
.\"If
.\".B fields=foo+bar
.\"is added, search keywords in fields foo and bar.
.\".TP
.\".B <category>/<hexadecinal id>
.\"CDDB query for CD matching category and id

.TP
.BR q " (or " EOF )
Quit CDDB query, see
.B MAIN MENU

.P
Once keywords have been passed as a query to CDDB, a list of matching
CD titles will be displayed. The user then needs to choose one:
.TP
.B <index>
Choose a CD in the current keywords query results list
.TP
.B V
View the list of CD matching the keywords
.TP
.B k
Start again CDDB query with different keywords
.TP
.BR q " (or " EOF )
Quit CDDB query, see
.B MAIN MENU

.P
Once a CD have been chosen, the user needs to choose a track
.TP
.B <index>
Choose a track of the current CD
.TP
.B <index> a
Choose a track and do not ask for confirmation anymore
.TP
.B a
Use default track and do not ask for confirmation anymore
.TP
.B E
Edit current CD common tags, see
.B EDITING MENU
.TP
.B v
View the list of CD matching the keywords
.TP
.B c
Change the CD chosen in keywords query results list
.TP
.B k
Start again CDDB query with different keywords
.TP
.BR q " (or " EOF )
Quit CDDB query, see
.B MAIN MENU

.P
Note that entering the CDDB menus again will go back to the previous
CD instead of asking the user to query again, so that an entire CD
may be tagged easily.



.SS PARSING MENU
When
.B --ask
is passed or when guessing, each matching will lead to
a confirmation message before tagging.
Available behaviors are:
.TP
.B y
Tag current file with current format. This is the default.
.TP
.B u
Tag current file with current format.
Then use current format for all remaining matching files.
When a non-matching file is reached, stop using this
preferred format.
.TP
.B a
Tag current file with current format.
Then, never asking for a confirmation anymore.
.TP
.B n
Don't tag current file with this format.
Try the next matching format on the current file.
.TP
.B p
When matching is done through combination of a path parser
and a basename parser, keep the basename parser and try the
next path parser on the current file.
.TP
.BR q " (or " EOF )
Stop trying to parse this file.



.SS EDITING MENU
It is possible to edit tags, either before tagging or file, or before
choosing a track in a CD obtained by CDDB.
The current value of all regular fields is shown and may be modified
by entering another value, deleted by entering
.BR <DELETE> ,
or cleared.

The behavior depends on the installed readline library.
If it is smart, the current value may be edited inline and an
history is available.
If not, pressing
.I <enter>
will keep the current value while
.I CLEAR
will empty it.
.I EOF
while cancel the editing of this single value.

Each field may be selected for edition by pressing its corresponding
letter in the format (see \fBFORMAT\fR).
Since there might be some non-standard tag names, it is also possible
to enter \fItag FOO\fR to modify tag \fIFOO\fR.

Editing ends by tagging (if \fIE\fR is pressed)
or canceling and return to confirmation menu (if \fIC\fR is pressed).

The other options are:
.TP
.B V
View the current values of tags
.TP
.B y
End edition, save changes, and return to previous menu
.TP
.BR q " (or " EOF )
Cancel edition, forget about changes, and return to previous menu



.SS RENAMING MENU
By default, before renaming, a confirmation is asked to the user.
You may bypass it by passing
.B --yes
on the command line.

If the rename format uses a field that is not defined,
a warning is shown and confirmation is always asked.

Available behaviors when renaming are:
.TP
.B y
Rename current file with current new filename.
This is the default.
.TP
.B a
Rename current file with current new filename.
Then, never asking for a renaming confirmation anymore.
.TP
.B e
Edit current new filename before renaming.
The behavior depends on the installed readline library.
If it is smart, the current value may be edited inline
and an history is available.
.TP
.BR q " (or " EOF )
Don't rename current file.
.TP
.B h
Show help about confirmation.




.SH FORMAT
User-specified formats must be a string composed of any characters
and the following special codes:
.RS

.I "%a"
to match the author.

.I "%A"
to match the album.

.I "%g"
to match the genre.

.I "%n"
to match the track number.

.I "%t"
to match the title.

.I "%d"
to match the date.

.I "%c"
to match the comment.

.I "%i"
to match anything and ignore it.

.I "%%"
to match %.

.RE
Additionaly, while renaming, the following codes are available:
.RS

.I "%F"
is replaced by the original basename of the file.

.I "%E"
is replaced by the original extension of the file.

.I "%P"
is replaced by the original path of the file.



.SH INTERNAL FORMATS
The internal format database is usually stored in
.IR /etc/lltag/formats .
The user may override this file by defining a
.IR $HOME/.lltag/formats .
If this file exists, the system-wide one is ignored.

See the manpage of
.I lltag_formats
or
.I /etc/lltag/formats
for details.




.SH CONFIGURATION FILES
lltag reads some configuration files before parsing command line options.
The system-wide configuration file is defined in
.I /etc/lltag/config
if it exists.

It also reads
.I $HOME/.lltag/config
if it exists.

The user may also add another configurable file with
.BR --config .

lltag may also generate a configuration with
.BR --gencfg .

See the manpage of
.I lltag_config
or the example of
.I config
file provided in the documentation for details.



.SH FILES
.RE
.I /etc/lltag/formats
.RS
System-wide internal format database.
See
.B INTERNAL FORMATS
for details.
.RE
.I $HOME/.lltag/formats
.RS
User internal format database. If it exists, the system-wide one is ignored.
.RE
.I $HOME/.lltag/edit_history
.RS
History of last entered values in the edition mode if the
.B Readline
library supports this feature.
.RE
.I /etc/lltag/config
.RS
System-wide configuration file, if it exists.
See
.B CONFIGURATION FILES
for details.
.RE
.I $HOME/.lltag/config
.RS
User configuration file.



.SH EXAMPLES
.RE
Show all tags for each OGG files in the current directory:
.RS
lltag -S *.ogg
.RE
Show only a selected list of tags for all files in all subdirectories:
.RS
lltag --show-tags artist,album,title,number -R .
.RE
Set an arbitrary tag in a file (only works with OGG vorbis or FLAC files):
.RS
lltag --tag foo=nil foo.ogg
.RE
Delete the foo tag from a file:
.RS
lltag --tag foo= bar.ogg
.RE
Set the ALBUM, ARTIST and GENRE tag values of the MP3 files in the current directory:
.RS
lltag --artist "Queen" --album "Innunendo" --genre "rock" --comment="very cool" *.mp3
.RE
Rename a file by assembling its current NUMBER, ARTIST and TITLE tag values:
.RS
lltag --no-tagging --rename "%n - %a - %t" foobar.ogg
.RE
Clear all tags in all FLAC files:
.RS
lltag --clear *.flac




.SH SEE ALSO
.PP
.BR lltag_config "(5), " lltag_formats (5)

The
.I howto.html
file provided within the documentation.




.SH AUTHOR
Brice Goglin
